.TH METADATA 1 "APRIL 2011" Linux "User Manuals"
.SH NAME
metadata \- extract RDF metadata for documents
.SH SYNOPSIS
.B metadata [OPTION..]
.I document
.SH DESCRIPTION
.B metadata
Extract the metadata from ePub, RDF/XML, HTML and other documents,
producing RDF statements or other metadata formats.
.SH OPTIONS
.IP "--ntriple"
Generate RDF N-Triple statements.
.IP "--turtle"
Generate RDF Turtle statements. NOTE: These statements are not in
a compact form.
.IP "--vorbis"
Generate VorbisComment metadata.
.SH AUTHOR
Reece H. Dunn <msclrhd@gmail.com>
