#!/usr/bin/python
#
# Tool for processing eSpeak phonemes.
#
# Copyright (C) 2014 Reece H. Dunn
#
# This file is part of cainteoir-engine.
#
# cainteoir-engine is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cainteoir-engine is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cainteoir-engine.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
import re

espeak_dir = os.environ['ESPEAK_DIR']

def read_file(filename):
	with open(filename) as f:
		for line in f:
			line = line.replace('\n', '')
			if line != '':
				yield line

def read_phonemes(filename):
	language = None
	data = []
	dictionary = re.compile('Dictionary ([a-z]+)_dict  [0-9\-]+')
	for line in read_file(filename):
		m = dictionary.match(line)
		if m:
			if language:
				yield (language, data)
			language = m.group(1)
			data = []
		else:
			data.extend(line.split())

data = dict(read_phonemes(os.path.join(espeak_dir, 'dictsource', 'dict_phonemes')))

for language, phonemes in data.items():
	with open(os.path.join('tests', 'phonemeset', 'espeak', '%s.phoneme' % language), 'w') as f:
		f.write('\n'.join(phonemes))
