#!/bin/bash
#
# Tool for sorting entries in a Cainteoir Text-to-Speech dictionary file.
#
# Copyright (C) 2013 Reece H. Dunn
#
# This file is part of cainteoir-engine.
#
# cainteoir-engine is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cainteoir-engine is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cainteoir-engine.  If not, see <http://www.gnu.org/licenses/>.

DICT=$1

cat ${DICT} | grep -P "^\." > /tmp/sorted
cat ${DICT} | grep -vP "^\." | sort -d -k1,1 | uniq >> /tmp/sorted

mv /tmp/sorted ${DICT}
